/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import clases.Drogueria;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;          
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author SP
 */
public class IngresarDatos extends javax.swing.JDialog {

    /**
     * Creates new form IngresarDatos
     */
    String ruta;
    ObjectOutputStream salida;
    ArrayList<Drogueria> Drogueria;
    int aux = 0;

    public IngresarDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        JButton botonesH[] = {cmdBuscar, cmdConservar};
        JButton botonesD[] = {cmdGuardar, cmdEliminar};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);

        ruta = "src/serializar/serializacion.txt";
        try {
            Drogueria = Helper.traerDatos(ruta);
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcadoDrogueria(salida, Drogueria);
        Helper.llenarTabla(tblMostrarDatos, ruta);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        cmdGuardar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdConservar = new javax.swing.JButton();
        cmdBuscar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrarDatos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Datos");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 2, 14), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Medicamento");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 31, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jLabel2.setText("Cantidad");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Precio");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 111, -1, -1));

        txtMedicamento.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtMedicamento.setForeground(new java.awt.Color(102, 102, 0));
        txtMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedicamentoKeyTyped(evt);
            }
        });
        jPanel2.add(txtMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 120, -1));

        txtCantidad.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(204, 0, 204));
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 120, -1));

        txtPrecio.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(255, 102, 102));
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 120, -1));

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 153));
        jLabel5.setText("Tipo");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        cmbTipo.setFont(new java.awt.Font("Traditional Arabic", 2, 14)); // NOI18N
        cmbTipo.setForeground(new java.awt.Color(204, 0, 204));
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Generico ", "Comercial" }));
        jPanel2.add(cmbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 120, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 190));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Galeria De Botones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 2, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdGuardar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        cmdGuardar.setForeground(new java.awt.Color(255, 153, 0));
        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        cmdEliminar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 80, 100, 30));

        cmdConservar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        cmdConservar.setForeground(new java.awt.Color(153, 153, 255));
        cmdConservar.setText("Conservar");
        cmdConservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConservarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdConservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 120, -1));

        cmdBuscar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        cmdBuscar.setText("Buscar");
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 120, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 250, 140));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mostrar Datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 18), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMostrarDatos.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        tblMostrarDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Medicamento", "Cantidad", "Precio", "Tipo"
            }
        ));
        tblMostrarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMostrarDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMostrarDatos);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 500, 290));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 520, 330));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/85a485429c131fd3d99b44cd6ff2d0c1.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 340));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicamentoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) || Character.isSpaceChar(c) || Character.isDigit(c)) {
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_txtMedicamentoKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c) || !Character.isDigit(c)) {
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c) || !Character.isDigit(c)) {
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        if (txtMedicamento.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese medicamento a comprar", 1);
            txtMedicamento.requestFocusInWindow();
        } else if (txtCantidad.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese cantidad a comprar", 1);
            txtCantidad.requestFocusInWindow();
        } else if (txtPrecio.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese precio del medicamento", 1);
            txtPrecio.requestFocusInWindow();
        } else { 
           try {
            String medicamento=txtMedicamento.getText(), cantidadmedicamento=txtCantidad.getText(), precio=txtPrecio.getText() , tipo=cmbTipo.getSelectedItem().toString() ;
            ArrayList<Drogueria> medicamentoActualizado;
            try {
                medicamento = txtMedicamento.getText();
                cantidadmedicamento = txtCantidad.getText();
                precio = txtPrecio.getText();
               
                
                tipo = cmbTipo.getSelectedItem().toString();

            } catch (Exception e) {
                Helper.mensaje(this,"Digite datos aptos para el sistema", 3);
            }
            if (txtMedicamento.getText().isEmpty() || txtCantidad.getText().isEmpty() || txtPrecio.getText().isEmpty()) {
                Helper.mensaje(this,"No se pueden dejar espacio en blanco",2);
            } else {

                if (aux == 0) {

                    Drogueria dondevirgilio = new Drogueria(medicamento, cantidadmedicamento, precio, tipo);

                    dondevirgilio.guardar(salida);
                    txtMedicamento.requestFocusInWindow();
                    Helper.mensaje(this,"Datos Guardados en el sistema",1);
                    Helper.llenarTabla(tblMostrarDatos, ruta);
                    limpiar();
                    

                } else {
                    medicamentoActualizado = Helper.actualizacionMedicamento(ruta,medicamento,cantidadmedicamento,precio,tipo);
                    salida = new ObjectOutputStream(new FileOutputStream(ruta));
                    Helper.volcadoDrogueria(salida, medicamentoActualizado);
                    Helper.llenarTabla(tblMostrarDatos, ruta);
                    Helper.mensaje(this,"Datos Actualizados en el sistema",1);

                    limpiar();
                }
            }
        } catch (FileNotFoundException ex) {
            System.out.println(ex.getMessage());
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        JButton botonesH[] = {cmdBuscar, cmdConservar};
        JButton botonesD[] = {cmdEliminar, cmdGuardar};
        
        
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
        
            /*try {
                String medicamento, cantidadmedicamento, Precio, tipo;
                medicamento = txtMedicamento.getText();
                cantidadmedicamento = txtCantidad.getText();
                Precio = txtPrecio.getText();
                tipo = cmbTipo.getSelectedItem().toString();

                ArrayList<Drogueria> actualizacionMedicamento;

                if (aux == 0) {

                    Drogueria dondevirgilio = new Drogueria(medicamento, cantidadmedicamento, Precio,tipo);
                    dondevirgilio.guardar(salida);
                    Helper.llenarTabla(tblMostrarDatos, ruta);
                    txtMedicamento.setText("");
                    txtCantidad.setText("");
                    txtPrecio.setText("");
                    txtMedicamento.requestFocusInWindow();

                } else {
                    actualizacionMedicamento = Helper.actualizacionMedicamento(ruta, medicamento, cantidadmedicamento, Precio,tipo);
                    salida = new ObjectOutputStream(new FileOutputStream(ruta));
                    Helper.volcadoDrogueria(salida, actualizacionMedicamento);
                    Helper.llenarTabla(tblMostrarDatos, ruta);
                    Helper.mensaje(this, "Medicamento actualizado en el sistema", 1);

                }
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
            {

            }*/
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdConservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConservarActionPerformed
        limpiar();
        JButton botonesH[] = {cmdBuscar, cmdConservar};
        JButton botonesD[] = {cmdGuardar, cmdEliminar};
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdConservarActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        /*int i, op;

        op = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar?", "Eliminar", JOptionPane.YES_NO_OPTION);

        if (op == JOptionPane.YES_OPTION) {

            try {
                i = tblMostrarDatos.getSelectedRow();
                Drogueria.remove(i);
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
                Helper.volcadoDrogueria(salida, Drogueria);
                Helper.llenarTabla(tblMostrarDatos, ruta);
                txtMedicamento.setText("");
                txtCantidad.setText("");
                txtPrecio.setText(""); 
                cmbTipo.setSelectedIndex(0); 
                txtMedicamento.requestFocusInWindow();
            } catch (FileNotFoundException ex) {
                Logger.getLogger(IngresarDatos.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(IngresarDatos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        JButton botonesH[] = {cmdBuscar, cmdConservar};
        JButton botonesD[] = {cmdGuardar, cmdEliminar};
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
        {
        } 
      */   
         int i, op;

        op = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar?", "Eliminar", JOptionPane.YES_NO_OPTION);

        if (op == JOptionPane.YES_OPTION) {

            try {
                i = tblMostrarDatos.getSelectedRow();
                Drogueria.remove(i);
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
                Helper.volcadoDrogueria(salida, Drogueria);
                Helper.llenarTabla(tblMostrarDatos, ruta);
                limpiar();
            } catch (FileNotFoundException ex) {
                System.out.println(ex.getMessage());
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        }
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void tblMostrarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMostrarDatosMouseClicked
        Drogueria dondevirgilio;
        int albin;
        Drogueria = Helper.traerDatos(ruta);
        albin = tblMostrarDatos.getSelectedRow();
        dondevirgilio = Drogueria.get(albin);

        txtMedicamento.setText(dondevirgilio.getMedicamento());
        txtCantidad.setText(dondevirgilio.getCantidadmedicamento());
        txtPrecio.setText(dondevirgilio.getPrecio());
       
        cmbTipo.setSelectedItem(dondevirgilio.getTipo());
        aux = 1;
        /*int dato;

        Drogueria dondevirgilio;
        ArrayList<Drogueria> personas = Helper.traerDatos(ruta);
        dato = tblMostrarDatos.getSelectedRow();

        dondevirgilio = personas.get(dato);

        txtMedicamento.setText(dondevirgilio.getMedicamento());
        txtCantidad.setText(dondevirgilio.getCantidadmedicamento());
        txtPrecio.setText(dondevirgilio.getPrecio()); 
        cmbTipo.setSelectedItem(dondevirgilio.getTipo()); 
      */
    }//GEN-LAST:event_tblMostrarDatosMouseClicked

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed
        String precio;
        precio = txtPrecio.getText();
        Drogueria p;
        if (Helper.buscarPreciomedicamento(precio, ruta)) {
            p = Helper.traerPreciomedicamento(precio, ruta);
            txtMedicamento.setText(p.getMedicamento());
            txtCantidad.setText(p.getCantidadmedicamento());

            aux = 1;
        } else {
            txtMedicamento.requestFocusInWindow();
            aux = 0;
        }
        JButton botonesH[] = {cmdGuardar, cmdConservar, cmdEliminar};
        JButton botonesD[] = {cmdBuscar};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);

    }//GEN-LAST:event_cmdBuscarActionPerformed
    public void limpiar() {
        txtMedicamento.setText("");
        txtCantidad.setText("");
        txtPrecio.setText(""); 
        cmbTipo.setSelectedIndex(0); 

        txtMedicamento.requestFocusInWindow();
        aux = 0;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IngresarDatos dialog = new IngresarDatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbTipo;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdConservar;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMostrarDatos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
