/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import clases.Drogueria;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SP
 */
public class IngresarDatos extends javax.swing.JDialog {

    /**
     * Creates new form IngresarDatos
     */
    String ruta;
    ObjectOutputStream salida;
    ArrayList<Drogueria> Drogueria;

    public IngresarDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        ruta = "src/serializar/serializacion.txt";
        try {
            Drogueria = Helper.traerDatos(ruta);
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcadoDrogueria(salida, Drogueria);
        Helper.llenarTabla(tblMostrarDatos, ruta);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmdGuardar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        cmdLimpiar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrarDatos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Datos");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 2, 14), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 102));
        jLabel1.setText("Medicamento");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 31, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jLabel2.setText("Cantidad");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 71, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Precio");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 111, -1, -1));

        txtMedicamento.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtMedicamento.setForeground(new java.awt.Color(102, 102, 0));
        txtMedicamento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMedicamentoKeyTyped(evt);
            }
        });
        jPanel2.add(txtMedicamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 120, -1));

        txtCantidad.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(204, 0, 204));
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 120, -1));

        txtPrecio.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(255, 102, 102));
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 120, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 250, 150));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Galeria De Botones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 2, 18), new java.awt.Color(0, 102, 102))); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdGuardar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        cmdGuardar.setForeground(new java.awt.Color(255, 153, 0));
        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, -1, -1));

        cmdEliminar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 80, 100, 30));

        cmdLimpiar.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        cmdLimpiar.setForeground(new java.awt.Color(153, 153, 255));
        cmdLimpiar.setText("Limpiar");
        cmdLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLimpiarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 250, 140));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mostrar Datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 2, 18), new java.awt.Color(153, 0, 153))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMostrarDatos.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        tblMostrarDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Medicamento", "Cantidad", "Precio"
            }
        ));
        tblMostrarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMostrarDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMostrarDatos);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 500, 260));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 520, 300));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/stock-of-medicine-600x400.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMedicamentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMedicamentoKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isLetter(c) || Character.isSpaceChar(c) || Character.isDigit(c)) {
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_txtMedicamentoKeyTyped

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c) || !Character.isDigit(c)) {
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
        char c = evt.getKeyChar();
        if (Character.isLetter(c) || Character.isSpaceChar(c) || !Character.isDigit(c)) {
            getToolkit();
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        String medicamento, cantidadmedicamento, preciomedicamento;

        if (txtMedicamento.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese medicamento a comprar", 1);
            txtMedicamento.requestFocusInWindow();
        } else if (txtCantidad.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese cantidad a comprar", 1);
            txtCantidad.requestFocusInWindow();
        } else if (txtPrecio.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese precio del medicamento", 1);
            txtPrecio.requestFocusInWindow();
        } else {
            medicamento = txtMedicamento.getText();
            cantidadmedicamento = txtCantidad.getText();
            preciomedicamento = txtPrecio.getText();

            Drogueria dondevirgilio = new Drogueria(medicamento, cantidadmedicamento, preciomedicamento);
            try {
                dondevirgilio.guardar(salida);
            } catch (IOException ex) {
                Logger.getLogger(Drogueria.class.getName()).log(Level.SEVERE, null, ex);
            }
            Helper.llenarTabla(tblMostrarDatos, ruta);

            txtMedicamento.setText("");
            txtCantidad.setText("");
            txtPrecio.setText("");
            txtMedicamento.requestFocusInWindow();
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLimpiarActionPerformed
        txtMedicamento.setText("");
        txtCantidad.setText("");
        txtPrecio.setText("");
        txtMedicamento.requestFocusInWindow();
    }//GEN-LAST:event_cmdLimpiarActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed
        int dato, mostrar;

        mostrar = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar esta llamada?", "Eliminar", JOptionPane.YES_NO_OPTION);

        ArrayList<Drogueria> llamadas = Helper.traerDatos(ruta);

        if (mostrar == JOptionPane.YES_OPTION) {
            dato = tblMostrarDatos.getSelectedRow();
            llamadas.remove(dato);
            try {
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
            } catch (FileNotFoundException ex) {
                Logger.getLogger(Drogueria.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Drogueria.class.getName()).log(Level.SEVERE, null, ex);
            }
            Helper.volcadoDrogueria(salida, Drogueria);
            Helper.llenarTabla(tblMostrarDatos, ruta);
     
            txtMedicamento.setText("");
            txtCantidad.setText("");
            txtPrecio.setText("");
            txtMedicamento.requestFocusInWindow();
        }
    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void tblMostrarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMostrarDatosMouseClicked
        int dato;

        Drogueria dondevirgilio;
        ArrayList<Drogueria> personas = Helper.traerDatos(ruta);
        dato = tblMostrarDatos.getSelectedRow();

        dondevirgilio = personas.get(dato);

        txtMedicamento.setText(dondevirgilio.getMedicamento());
        txtCantidad.setText(dondevirgilio.getCantidadmedicamento());
        txtPrecio.setText(dondevirgilio.getPrecio());
    }//GEN-LAST:event_tblMostrarDatosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IngresarDatos dialog = new IngresarDatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JButton cmdLimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMostrarDatos;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
