/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clases.Helper;
import clases.Persona;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author SP
 */
public class IngresarDatosPersona extends javax.swing.JDialog {

    /**
     * Creates new form IngresarDatosPersona
     */
    String ruta;
    ObjectOutputStream salida;
    ArrayList<Persona> personas;
    int aux = 0;

    public IngresarDatosPersona(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        JButton botonesH[] = {cmdBuscar, cmdConservar};
        JButton botonesD[] = {cmdGuardar, cmdEliminar};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
        ruta = "src/serializar/serializacion_persona.txt";
        try {
            personas = Helper.traerDatos(ruta);
            salida = new ObjectOutputStream(new FileOutputStream(ruta));
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        Helper.volcadoDrogueria(salida, personas);
        Helper.llenarTablaPersona(tblMostrarDatos, ruta);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        cmbEdad = new javax.swing.JComboBox();
        cmbSexo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        cmdGuardar = new javax.swing.JButton();
        cmdBuscar = new javax.swing.JButton();
        cmdConservar = new javax.swing.JButton();
        cmdEliminar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMostrarDatos = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Agregar Personas");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Persona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 2, 18))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 153));
        jLabel1.setText("Cedula");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 37, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Nombre");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 75, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 153, 0));
        jLabel3.setText("Apellido");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 113, -1, -1));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 51, 51));
        jLabel4.setText("Edad");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 148, 60, -1));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel5.setText("Sexo");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 50, 30));
        jPanel2.add(txtCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 34, 145, -1));
        jPanel2.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 72, 145, -1));
        jPanel2.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 110, 145, -1));

        cmbEdad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "18 años ", "19 años ", "20 años ", "21 años ", "22 años", "23 años", "24 años ", "25 años ", "26 años ", "27 años ", "28 años", "29 años", "30 años", "31 años", "32 años", "33 años ", "34 años ", "35 años", "36 años ", "37 años ", "38 años ", "39 años ", "40 años", "41 años", "42 años", "43 años", "44 años", "45 años", "46 años", "47 años", "48 años", "49 años", "50 años", "51 años", "52 años", "53 años", "54 años", "55 años", "56 años", "57 años", "58 años", "59 años", "60 años", "61 años", "62 años", "63 años", "64 años", "65 años", "66 años", "67 años", "68 años ", "69 años", "70 años", "71 años", "72 años", "73 años", "74 años ", "75 años ", "76 años", "77 años", "78 años", "79 años", "80 años", "81 años", "82 años", "83 años", "84 años", "85 años ", "86 años ", "87 años", "88 años", "89 años", "90 años", "91 años", "92 años", "93 años", "94 años", "95 años", "96 años", "97 años ", "98 años", "99 años ", "100 años" }));
        jPanel2.add(cmbEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 148, 145, -1));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino ", "Femenino ", "Bola " }));
        jPanel2.add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 186, 145, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 240, 220));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Galeria De Botones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 2, 18), new java.awt.Color(204, 0, 153))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdGuardar.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        cmdGuardar.setForeground(new java.awt.Color(0, 153, 153));
        cmdGuardar.setText("Guardar");
        cmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdGuardarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 23, 105, -1));

        cmdBuscar.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        cmdBuscar.setText("Buscar");
        cmdBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBuscarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 69, 105, -1));

        cmdConservar.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        cmdConservar.setForeground(new java.awt.Color(153, 0, 153));
        cmdConservar.setText("Conservar");
        cmdConservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConservarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdConservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 122, -1, -1));

        cmdEliminar.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        cmdEliminar.setForeground(new java.awt.Color(255, 153, 0));
        cmdEliminar.setText("Eliminar");
        cmdEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEliminarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 175, 105, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 190, 220));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Mostrar Datos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT", 2, 24), new java.awt.Color(204, 0, 0))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblMostrarDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.. ", "C.C", "Nombre", "Apellido", "Edad", "Sexo"
            }
        ));
        tblMostrarDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMostrarDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMostrarDatos);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 510, 200));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 530, 250));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/41179571-Road-trip-fun-Group-of-young-happy-people-enjoying-time-together--Stock-Photo.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdGuardarActionPerformed
        if (txtCedula.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese cedula de la persona", 1);
            txtNombre.requestFocusInWindow();
        } else if (txtNombre.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese nombre de la persona", 1);
            txtNombre.requestFocusInWindow();
        } else if (txtApellido.getText().trim().isEmpty()) {
            Helper.mensaje(this, "Ingrese apellido de la persona", 1);
            txtApellido.requestFocusInWindow();
        } else {
            try {
                String cedula = txtCedula.getText(), nombre = txtNombre.getText(), apellido = txtApellido.getText(), edad = cmbEdad.getSelectedItem().toString(), sexo = cmbSexo.getSelectedItem().toString();
                ArrayList<Persona> personaActualizada;
                try {
                    cedula = txtCedula.getText();
                    nombre = txtNombre.getText();
                    apellido = txtApellido.getText();

                    edad = cmbEdad.getSelectedItem().toString();
                    sexo = cmbSexo.getSelectedItem().toString();
                } catch (Exception e) {
                    Helper.mensaje(this, "Digite datos aptos para el sistema", 3);
                }
                if (txtCedula.getText().isEmpty() || txtNombre.getText().isEmpty() || txtApellido.getText().isEmpty()) {
                    Helper.mensaje(this, "No se pueden dejar espacio en blanco", 2);
                } else {
                    if (aux == 0) {

                        Persona P = new Persona(cedula, nombre, apellido, edad, sexo);
                        P.guardar(salida);
                        txtCedula.requestFocusInWindow();
                        Helper.mensaje(this, "Datos Guardados en el sistema", 1);
                        Helper.llenarTablaPersona(tblMostrarDatos, ruta);
                        limpiar();
                    } else {
                        personaActualizada = Helper.actualizarPersona(ruta, cedula, nombre, apellido, edad, sexo);
                        salida = new ObjectOutputStream(new FileOutputStream(ruta));
                        Helper.volcadoDrogueria(salida, personaActualizada);
                        Helper.llenarTablaPersona(tblMostrarDatos, ruta);
                        Helper.mensaje(this, "Datos Actualizados en el sistema", 1);

                        limpiar();
                    }
                }
            } catch (FileNotFoundException ex) {
                System.out.println(ex.getMessage());
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
            JButton botonesH[] = {cmdBuscar, cmdConservar};
            JButton botonesD[] = {cmdEliminar, cmdGuardar};

            Helper.habilitarBotones(botonesH);
            Helper.deshabilitarBotones(botonesD);
        }
    }//GEN-LAST:event_cmdGuardarActionPerformed

    private void cmdBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBuscarActionPerformed

        String cedula;
        cedula = txtCedula.getText();
        Persona p;
        if (Helper.buscarPersonaPorCedula(cedula, ruta)) {
            p = Helper.traerPersonaCedula(cedula, ruta);
            txtNombre.setText(p.getNombre());
            txtApellido.setText(p.getApellido());
            cmbEdad.setSelectedItem(p.getEdad());
            cmbSexo.setSelectedItem(p.getSexo());

            aux = 1;
        } else {
            txtCedula.requestFocusInWindow();
            aux = 0;
        }
        JButton botonesH[] = {cmdGuardar, cmdConservar, cmdEliminar};
        JButton botonesD[] = {cmdBuscar};

        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);
    }//GEN-LAST:event_cmdBuscarActionPerformed

    private void cmdConservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConservarActionPerformed

        limpiar();
        JButton botonesH[] = {cmdBuscar, cmdConservar};
        JButton botonesD[] = {cmdGuardar, cmdEliminar};
        Helper.habilitarBotones(botonesH);
        Helper.deshabilitarBotones(botonesD);    
    }//GEN-LAST:event_cmdConservarActionPerformed

    private void cmdEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEliminarActionPerformed

        int i, op;

        op = JOptionPane.showConfirmDialog(this, "¿Seguro que desea eliminar?", "Eliminar", JOptionPane.YES_NO_OPTION);
        if (op == JOptionPane.YES_OPTION) {

            try {
                i = tblMostrarDatos.getSelectedRow();
                personas.remove(i);
                salida = new ObjectOutputStream(new FileOutputStream(ruta));
                Helper.volcadoDrogueria(salida, personas);
                Helper.llenarTabla(tblMostrarDatos, ruta);
                limpiar();
            } catch (FileNotFoundException ex) {
                System.out.println(ex.getMessage());
            } catch (IOException ex) {
                System.out.println(ex.getMessage());
            }
        }

    }//GEN-LAST:event_cmdEliminarActionPerformed

    private void tblMostrarDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMostrarDatosMouseClicked

        Persona p;
        int i;
        personas = Helper.traerDatos(ruta);
        i = tblMostrarDatos.getSelectedRow();
        p = personas.get(i);

        txtCedula.setText(p.getCedula());
        txtNombre.setText(p.getNombre());
        txtApellido.setText(p.getApellido());
        cmbEdad.setSelectedItem(p.getEdad());
        cmbSexo.setSelectedItem(p.getSexo());
        aux = 1;    
    }//GEN-LAST:event_tblMostrarDatosMouseClicked

    public void limpiar() {
        txtCedula.setText("");
        txtNombre.setText("");
        txtApellido.setText("");
        cmbEdad.setSelectedIndex(0);
        cmbSexo.setSelectedIndex(0);

        txtCedula.requestFocusInWindow();
        aux = 0;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IngresarDatosPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IngresarDatosPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IngresarDatosPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IngresarDatosPersona.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IngresarDatosPersona dialog = new IngresarDatosPersona(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbEdad;
    private javax.swing.JComboBox cmbSexo;
    private javax.swing.JButton cmdBuscar;
    private javax.swing.JButton cmdConservar;
    private javax.swing.JButton cmdEliminar;
    private javax.swing.JButton cmdGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMostrarDatos;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}   
