/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;    

/**
 *   
 * @author SP
 */
public class Presentacion_Proyecto extends javax.swing.JFrame {

    /**
     * Creates new form Presentacion_Proyecto
     */
    public Presentacion_Proyecto() {
        initComponents();                                 
    }    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombreProyecto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNombrePresentador = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAsignatura = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGrupo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSemestre = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtParla = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        cmbDecision = new javax.swing.JComboBox();
        cmdConfirmar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Presentacion");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos-Presentacion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 2, 18), new java.awt.Color(255, 204, 0))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre Proyecto:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txtNombreProyecto.setEditable(false);
        txtNombreProyecto.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtNombreProyecto.setForeground(new java.awt.Color(204, 0, 204));
        txtNombreProyecto.setText(" Drogueria La Guaca");
        jPanel2.add(txtNombreProyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 160, 30));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre Presentador:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        txtNombrePresentador.setEditable(false);
        txtNombrePresentador.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtNombrePresentador.setText("Albin Nuñez");
        jPanel2.add(txtNombrePresentador, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 160, -1));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Asignatura:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        txtAsignatura.setEditable(false);
        txtAsignatura.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtAsignatura.setForeground(new java.awt.Color(255, 153, 0));
        txtAsignatura.setText("Algoritmos I");
        jPanel2.add(txtAsignatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 160, -1));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Grupo:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        txtGrupo.setEditable(false);
        txtGrupo.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtGrupo.setForeground(new java.awt.Color(0, 51, 204));
        txtGrupo.setText("AD");
        jPanel2.add(txtGrupo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 160, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Semestre:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        txtSemestre.setEditable(false);
        txtSemestre.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtSemestre.setForeground(new java.awt.Color(0, 153, 153));
        txtSemestre.setText("Dos");
        jPanel2.add(txtSemestre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 160, -1));

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Parla:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 60, -1));

        txtParla.setEditable(false);
        txtParla.setFont(new java.awt.Font("Tw Cen MT", 2, 18)); // NOI18N
        txtParla.setForeground(new java.awt.Color(255, 0, 255));
        txtParla.setText("Publico Sala 5");
        jPanel2.add(txtParla, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 160, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 280));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "¿ Que Desea Hacer ?", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Traditional Arabic", 2, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbDecision.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inicio Proyecto ", "No Mirar Proyecto" }));
        jPanel3.add(cmbDecision, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        cmdConfirmar.setText("Confirmar");
        cmdConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConfirmarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdConfirmar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 100, 230, 80));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/carabina-con-mira-telescopica-1010 (1).jpg"))); // NOI18N
        jLabel7.setText("jLabel7");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConfirmarActionPerformed
      int op = cmbDecision.getSelectedIndex();

        switch (op) {
            case 0:
                Bienvenidos Principal = new Bienvenidos();
                Principal.setVisible(true); 
                dispose();
             break;
            case 1:
                System.exit(0);
                break;          
        }
    }//GEN-LAST:event_cmdConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentacion_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentacion_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentacion_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentacion_Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentacion_Proyecto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbDecision;
    private javax.swing.JButton cmdConfirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtAsignatura;
    private javax.swing.JTextField txtGrupo;
    private javax.swing.JTextField txtNombrePresentador;
    private javax.swing.JTextField txtNombreProyecto;
    private javax.swing.JTextField txtParla;
    private javax.swing.JTextField txtSemestre;
    // End of variables declaration//GEN-END:variables
}
